In [ ]:
%pip install ipython-sql pymysql jupysql duckdb-engine grpcio toml cryptography

In [ ]:
%conda install mysqlclient -c conda-forge --quiet

In [1]:
%%bash

docker compose -f /home/brijeshdhaker/IdeaProjects/bd-python-module/docker-compose.yml up -d mysqlserver

 Container mysqlserver Creating
 Container mysqlserver Created
 Container mysqlserver Starting
 Container mysqlserver Started

##### Setup User & Databases


```

In [ ]:
%load_ext sql

In [ ]:
  %reload_ext sql

In [ ]:
%sqlcmd connect

In [ ]:
%sql --section mysql

In [ ]:
%sql engine

In [ ]:
%sql mysql+pymysql://mysqladmin:paSSW0rd@mysqlserver.sandbox.net:3306/SANDBOXDB

In [ ]:
# No Need to Run This Again
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

In [10]:
%%sql 
show databases;

Running query in 'mysql'

6 rows affected.

             Database
0              PUBLIC
1           SANDBOXDB
2  information_schema
3               mysql
4  performance_schema
5                 sys

In [11]:
%%sql 

USE SANDBOXDB;

Running query in 'mysql'

Empty DataFrame
Columns: []
Index: []

In [12]:
%%sql 
show tables;

Running query in 'mysql'

Empty DataFrame
Columns: [Tables_in_SANDBOXDB]
Index: []

In [ ]:
%sql select * from NEETASTUDIO.CUSTOMER_ENQUIRIES LIMIT 5

In [ ]:
%%sql
 
select * from NEETASTUDIO.CUSTOMER_ENQUIRIES LIMIT 5

In [13]:
%%sql
 
SELECT SUBSTRING_INDEX('www.mysql.com', '.', 2);

Running query in 'mysql'

1 rows affected.

  SUBSTRING_INDEX('www.mysql.com', '.', 2)
0                                www.mysql

In [14]:
%%sql
 
SELECT SUBSTRING_INDEX('www.mysql.com', '.', -2);

Running query in 'mysql'

1 rows affected.

  SUBSTRING_INDEX('www.mysql.com', '.', -2)
0                                 mysql.com

In [ ]:
%%sql

SELECT 
    SUBSTRING_INDEX('www.mysql.com', '.', 1) AS W1,
    SUBSTRING_INDEX(SUBSTRING_INDEX('www.mysql.com', '.', 2), '.', -1) AS W2,
    SUBSTRING_INDEX(SUBSTRING_INDEX('www.mysql.com', '.', 3), '.', -1) AS W3

In [ ]:
%%bash

sqlite3mysql -f /home/brijeshdhaker/IdeaProjects/bd-notebooks-module/notebooks/mysql/Chinook_Sqlite.sqlite -u mysqladmin -p -d SANDBOXDB -h mysqlserver.sandbox.net

In [ ]:
%%bash

mysqldump -u root -p SANDBOXDB > /apps/SANDBOXDB_full_db_backup.sql

mysqldump -u mysqladmin -p --no-create-info SANDBOXDB > /apps/data_only.sql

In [ ]:
%%bash

mysql -u root -p SANDBOXDB < /apps/SANDBOXDB_full_db_backup.sql