In [ ]:
%pip install ipython-sql pymysql jupysql duckdb-engine grpcio toml cryptography

In [ ]:
%conda install mysqlclient -c conda-forge --quiet

In [1]:
%%bash

docker compose -f /home/brijeshdhaker/IdeaProjects/bd-python-module/docker-compose.yml up -d mysqlserver

 Container mysqlserver Creating
 Container mysqlserver Created
 Container mysqlserver Starting
 Container mysqlserver Started

##### Setup User & Databases


```

In [ ]:
%load_ext sql

In [ ]:
%reload_ext sql

In [ ]:
%sqlcmd connect

In [ ]:
%sql --section mysql

In [ ]:
%sql engine

In [ ]:
%sql mysql+pymysql://mysqladmin:paSSW0rd@mysqlserver.sandbox.net:3306/SANDBOXDB

In [ ]:
# No Need to Run This Again
%config SqlMagic.style = '_DEPRECATED_DEFAULT'
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False
%config SqlMagic.autocommit=False
%config SqlMagic.displaylimit = 25
%config SqlMagic.dsn_filename
# %config SqlMagic.named_parameters = True

In [ ]:
%sql --connections

In [ ]:
%sqlcmd tables
%sqlcmd tables --schema schema

In [ ]:
%sqlcmd columns --table coordinates
%sqlcmd columns -t people
%sqlcmd columns --table numbers --schema some_schema

table = "numbers"
schema = "some_schema"
%sqlcmd columns --table {{table}} --schema {{schema}}

In [ ]:
%sqlcmd explore --table "yellow_tripdata_2021.parquet"

In [ ]:
table_name = "yellow_tripdata_2021.parquet"
%sqlcmd explore --table {{table_name}}

##### Data Profiling

In [ ]:
%%sql
CREATE TABLE taxi_trips AS
SELECT * FROM 'yellow_tripdata_2021-01.parquet'

In [ ]:
%sqlcmd profile --table taxi_trips

In [ ]:
%sqlcmd profile --table taxi_trips --output my-report.html

In [ ]:
from IPython.display import HTML

HTML("my-report.html")

In [ ]:
%sqlcmd profile --table trips --schema some_schema

table = "trips"
schema = "some_schema"
output = "my-report.html"

%sqlcmd profile --table {{table}} --schema {{schema}} --output {{output}}

In [ ]:
%sql sqlite:///one.db --alias one
%sql sqlite:///two.db --alias two

%sql one
%sql two

In [ ]:
%sql --close one
%sql --close two

In [ ]:
%sql -l

In [ ]:
%%sql two
result <<
SELECT * FROM two

In [ ]:
some_engine = create_engine("sqlite:///some.db")
%sql some_engine

In [ ]:
sex = "MALE"

In [ ]:
%%sql
SELECT *
FROM penguins.csv
WHERE  sex = '{{sex}}'

In [ ]:
dynamic_limit = 5
dynamic_column = "island, sex"

%sql SELECT {{dynamic_column}} FROM penguins.csv LIMIT {{dynamic_limit}}

In [ ]:
sex = ("MALE", "FEMALE")

In [ ]:
%%sql --save avg_body_mass
{% set islands = ["Torgersen", "Biscoe", "Dream"] %}
select
    sex,
    {% for island in islands %}
    avg(case when island = '{{island}}' then body_mass_g end) as {{island}}_body_mass_g,
    {% endfor %}
from penguins.csv
where sex in {{sex}}
group by sex

In [ ]:
final = %sqlcmd snippets avg_body_mass
print(final)

In [10]:
%%sql 
show databases;

Running query in 'mysql'

6 rows affected.

             Database
0              PUBLIC
1           SANDBOXDB
2  information_schema
3               mysql
4  performance_schema
5                 sys

In [11]:
%%sql 

USE SANDBOXDB;

Running query in 'mysql'

Empty DataFrame
Columns: []
Index: []

In [12]:
%%sql 
show tables;

Running query in 'mysql'

Empty DataFrame
Columns: [Tables_in_SANDBOXDB]
Index: []

In [ ]:
%sql select * from NEETASTUDIO.CUSTOMER_ENQUIRIES LIMIT 5

In [ ]:
%%sql
 
select * from NEETASTUDIO.CUSTOMER_ENQUIRIES LIMIT 5

In [13]:
%%sql
 
SELECT SUBSTRING_INDEX('www.mysql.com', '.', 2);

Running query in 'mysql'

1 rows affected.

  SUBSTRING_INDEX('www.mysql.com', '.', 2)
0                                www.mysql

In [14]:
%%sql
 
SELECT SUBSTRING_INDEX('www.mysql.com', '.', -2);

Running query in 'mysql'

1 rows affected.

  SUBSTRING_INDEX('www.mysql.com', '.', -2)
0                                 mysql.com

In [ ]:
%%sql

SELECT 
    SUBSTRING_INDEX('www.mysql.com', '.', 1) AS W1,
    SUBSTRING_INDEX(SUBSTRING_INDEX('www.mysql.com', '.', 2), '.', -1) AS W2,
    SUBSTRING_INDEX(SUBSTRING_INDEX('www.mysql.com', '.', 3), '.', -1) AS W3

In [ ]:
%%bash

sqlite3mysql -f /home/brijeshdhaker/IdeaProjects/bd-notebooks-module/notebooks/mysql/Chinook_Sqlite.sqlite -u mysqladmin -p -d SANDBOXDB -h mysqlserver.sandbox.net

In [ ]:
%%bash

mysqldump -u root -p SANDBOXDB > /apps/SANDBOXDB_full_db_backup.sql

mysqldump -u mysqladmin -p --no-create-info SANDBOXDB > /apps/data_only.sql

In [ ]:
%%bash

mysql -u root -p SANDBOXDB < /apps/SANDBOXDB_full_db_backup.sql